### ISSUE TITLE
AttributeError: module 'genesis' has no attribute 'init'

### ISSUE THREAD

**Issue by quanting-xie** [Genesis-Embodied-AI/Genesis#113]
Traceback (most recent call last):
  File "/home/quanting/Genesis/examples/drone/fly.py", line 56, in <module>
    main()
  File "/home/quanting/Genesis/examples/drone/fly.py", line 17, in main
    gs.init(backend=gs.cpu)
    ^^^^^^^
AttributeError: module 'genesis' has no attribute 'init'

**Comment by quanting-xie** [comment]
Download the correct genesis

**Comment by shifuxiao** [comment]
can you solve this problem?I also meet this problem.
