### ISSUE TITLE
    'iwrk': array([], dfitpack_int), 'u': array([], float), TypeError

### ISSUE THREAD

**Issue by supernba123** [Genesis-Embodied-AI/Genesis#117]
Device: Apple MacBook Pro
Processor: M3 Max
RAM: 48GB
Python: 3.10.16
Using conda

Running this code:
```
import genesis as gs
gs.init(backend=gs.cpu)

scene = gs.Scene(show_viewer=True)
plane = scene.add_entity(gs.morphs.Plane())
franka = scene.add_entity(
    gs.morphs.MJCF(file='xml/franka_emika_panda/panda.xml'),
)

scene.build()

for i in range(1000):
    scene.step()
```

and I got this:

Traceback (most recent call last):
  File "/Users/user/Downloads/genesis/demo.py", line 1, in <module>
    import genesis as gs
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/__init__.py", line 274, in <module>
    from .engine.scene import Scene
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/engine/scene.py", line 5, in <module>
    from genesis.engine.entities import Emitter
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/engine/entities/__init__.py", line 1, in <module>
    from .avatar_entity import AvatarEntity
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/engine/entities/avatar_entity/__init__.py", line 1, in <module>
    from .avatar_entity import AvatarEntity
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/engine/entities/avatar_entity/avatar_entity.py", line 3, in <module>
    from ..rigid_entity import RigidEntity
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/engine/entities/rigid_entity/__init__.py", line 1, in <module>
    from .rigid_entity import RigidEntity
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/engine/entities/rigid_entity/rigid_entity.py", line 10, in <module>
    from genesis.utils import terrain as tu
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/utils/terrain.py", line 5, in <module>
    from genesis.ext.isaacgym import terrain_utils as isaacgym_terrain_utils
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/genesis/ext/isaacgym/terrain_utils.py", line 10, in <module>
    from scipy import interpolate
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genesis/lib/python3.10/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError

anyone got same issues?

**Comment by saprrow** [comment]
It's due numpy 2.0 has been installed.
Just pip uninstall numpy several times untill it show no numpy is installed. Then install numpy 1.X like  `pip install numpy==1.25.1`
