### ISSUE TITLE
AttributeError: function 'glGetUniformLocation' not found

### ISSUE THREAD

**Issue by mayurshri** [Genesis-Embodied-AI/Genesis#143]
Getting this error after running test.py.

import genesis as gs
gs.init(backend=gs.cpu)

scene = gs.Scene(show_viewer=True)
plane = scene.add_entity(gs.morphs.Plane())
franka = scene.add_entity(
    gs.morphs.MJCF(file='xml/franka_emika_panda/panda.xml'),
)

scene.build()

for i in range(1000):
    scene.step()

This is what it says

 File "E:\Genesis-AI\test.py", line 10, in <module>
    scene.build()
  File "C:\Users\may_s\lib\site-packages\genesis\utils\misc.py", line 38, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\may_s\lib\site-packages\genesis\engine\scene.py", line 556, in build
    self._visualizer.build()
  File "C:\Users\may_s\lib\site-packages\genesis\vis\visualizer.py", line 101, in build
    self._context.build(self._scene)
  File "C:\Users\may_s\lib\site-packages\genesis\vis\rasterizer_context.py", line 70, in build
    self.jit = JITRenderer(self._scene, [], [])
  File "C:\Users\may_s\lib\site-packages\genesis\ext\pyrender\jit_render.py", line 201, in __init__
    self.gen_func_ptr()
  File "C:\Users\may_s\lib\site-packages\genesis\ext\pyrender\jit_render.py", line 354, in gen_func_ptr
    self.gl = GLWrapper()
  File "C:\Users\may_s\lib\site-packages\genesis\ext\pyrender\numba_gl_wrapper.py", line 24, in __init__
    load_func("glGetUniformLocation", GLint, GLuint, GLvoidp)
  File "C:\Users\may_s\lib\site-packages\genesis\ext\pyrender\numba_gl_wrapper.py", line 52, in load_func
    func_ptr = GL.platform.ctypesloader.buildFunction(
  File "C:\Users\may_s\lib\site-packages\OpenGL\platform\ctypesloader.py", line 96, in buildFunction
    return functionType( (name, dll), )
AttributeError: function 'glGetUniformLocation' not found

**Comment by lyraestar** [comment]
I also get this error

**Comment by manuelgardina** [comment]
yep, same

**Comment by LucaSalesi98** [comment]
the same here with windows 11

**Comment by MJGoulard** [comment]
Same

**Comment by Sau1707** [comment]
Same

**Comment by zhouxian** [comment]
What OS are you on?

**Comment by tinypumpkin** [comment]
Traceback (most recent call last):
  File "f:\genesis\temp.py", line 12, in <module>
    scene.build()
  File "D:\Anaconda\Lib\site-packages\genesis\utils\misc.py", line 38, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\genesis\engine\scene.py", line 556, in build
    self._visualizer.build()
  File "D:\Anaconda\Lib\site-packages\genesis\vis\visualizer.py", line 101, in build
    self._context.build(self._scene)
  File "D:\Anaconda\Lib\site-packages\genesis\vis\rasterizer_context.py", line 70, in build
    self.jit = JITRenderer(self._scene, [], [])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\genesis\ext\pyrender\jit_render.py", line 201, in __init__
    self.gen_func_ptr()
  File "D:\Anaconda\Lib\site-packages\genesis\ext\pyrender\jit_render.py", line 354, in gen_func_ptr
    self.gl = GLWrapper()
              ^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\genesis\ext\pyrender\numba_gl_wrapper.py", line 24, in __init__
    load_func("glGetUniformLocation", GLint, GLuint, GLvoidp)
  File "D:\Anaconda\Lib\site-packages\genesis\ext\pyrender\numba_gl_wrapper.py", line 52, in load_func
    func_ptr = GL.platform.ctypesloader.buildFunction(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\OpenGL\platform\ctypesloader.py", line 96, in buildFunction
    return functionType( (name, dll), )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function 'glGetUniformLocation' not found ，I got this

**Comment by tinypumpkin** [comment]
win11 , linux is ok ？

**Comment by simlabsoft** [comment]
Same on Windows 11

**Comment by CharlesCNorton** [comment]
same

**Comment by ziyanx02** [comment]
Close as a duplicate. Please refer to #12 for more information.

**Comment by walterf25** [comment]
I also get the same error when trying to run every example, only if I set the following to true
`show_viewer=True`
I'm running on windows 10, python 3.10, is there a work around for this?

**Comment by hadisaab2** [comment]
same error

**Comment by dkswndud1992** [comment]
same...

**Comment by CarlosMagni** [comment]
same

**Comment by ehsanecc** [comment]
Same, [here](https://genesis-world.readthedocs.io/en/latest/user_guide/overview/installation.html#prerequisites) they stated that **Interactive Viewer** is not available on windows so `show_viewer` should be `False` for windows.
