### ISSUE TITLE
RuntimeError: Validation failure with active samplers in Genesis rendering pipeline

### ISSUE THREAD

**Issue by m4s1t4** [Genesis-Embodied-AI/Genesis#74]
I encountered a RuntimeError while running a script using the Genesis library. The error is related to OpenGL shader validation, where active samplers with different types are assigned to the same texture image unit. Below is the full traceback:
```bash
Exception in thread Thread-2 (_init_and_start_app):
Traceback (most recent call last):
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/viewer.py", line 1149, in _init_and_start_app
    pyglet.clock.tick()
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/pyglet/clock.py", line 528, in tick
    return _default.tick(poll)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/pyglet/clock.py", line 270, in tick
    self.call_scheduled_functions(delta_t)
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/pyglet/clock.py", line 217, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/viewer.py", line 941, in _time_event
    self.on_draw()
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/viewer.py", line 640, in on_draw
    self._render()
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/viewer.py", line 1086, in _render
    retval = renderer.render(self.scene, flags, seg_node_map=seg_node_map)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/renderer.py", line 168, in render
    retval = self._forward_pass(scene, flags, seg_node_map=seg_node_map)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/renderer.py", line 534, in _forward_pass
    self.jit.forward_pass(
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/jit_render.py", line 708, in forward_pass
    self.load_programs(renderer, flags, program_flags)
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/jit_render.py", line 349, in load_programs
    program = renderer._get_primitive_program(primitive, flags, program_flags)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/renderer.py", line 1142, in _get_primitive_program
    program._add_to_context()
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/genesis/ext/pyrender/shader_program.py", line 125, in _add_to_context
    self._program_id = gl_shader_utils.compileProgram(*shader_ids, validate=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/OpenGL/GL/shaders.py", line 196, in compileProgram
    program.check_validate()
  File "/home/m4s1t4/anaconda3/envs/genesis/lib/python3.11/site-packages/OpenGL/GL/shaders.py", line 105, in check_validate
    raise RuntimeError(
RuntimeError: Validation failure (0): b'active samplers with a different type refer to the same texture image unit'
```
## Steps to Reproduce:

1. Install Genesis library and its dependencies.
2. Use the following script to initialize a scene with a camera and an object:
```python
import numpy as np
import genesis as gs

gs.init(backend=gs.cpu)

scene = gs.Scene(
    show_viewer=True,
    viewer_options=gs.options.ViewerOptions(
        res=(1280, 960),
        camera_pos=(3.5, 0.0, 2.5),
        camera_lookat=(0.0, 0.0, 0.5),
        camera_fov=40,
        max_FPS=60,
    ),
    vis_options=gs.options.VisOptions(
        show_world_frame=True,
        world_frame_size=1.0,
        show_link_frame=False,
        show_cameras=False,
        plane_reflection=True,
        ambient_light=(0.1, 0.1, 0.1),
    ),
    renderer=gs.renderers.Rasterizer(),
)

plane = scene.add_entity(
    gs.morphs.Plane(),
)
franka = scene.add_entity(
    gs.morphs.MJCF(file="xml/franka_emika_panda/panda.xml"),
)

cam = scene.add_camera(
    res=(640, 480),
    pos=(3.5, 0.0, 2.5),
    lookat=(0, 0, 0.5),
    fov=30,
    GUI=False,
)

scene.build()

cam.start_recording()
for i in range(120):
    scene.step()
    cam.set_pose(
        pos=(3.0 * np.sin(i / 60), 3.0 * np.cos(i / 60), 2.5),
        lookat=(0, 0, 0.5),
    )
    cam.render()
cam.stop_recording(save_to_filename="video.mp4", fps=60)
```
3. Run the script in an environment with the latest version of Genesis and its dependencies.

**Comment by m4s1t4** [comment]
I resolved the issue, I just need to update PyOpenGL to 3.1.7
