### ISSUE TITLE
EOFError: Ran out of input when test hello genesis

### ISSUE THREAD

**Issue by Michel-wei** [Genesis-Embodied-AI/Genesis#98]
hello.py
import genesis as gs
gs.init(backend=gs.cpu)
scene = gs.Scene(
    sim_options=gs.options.SimOptions(
        dt=0.01,
        gravity=(0, 0, -10.0),
    ),
    show_viewer=True,
    viewer_options=gs.options.ViewerOptions(
        camera_pos=(3.5, 0.0, 2.5),
        camera_lookat=(0.0, 0.0, 0.5),
        camera_fov=40,
    ),
)
plane = scene.add_entity(gs.morphs.Plane())

virtual-machine:~/Genesis$ /usr/bin/python3.10 /home/Genesis/hello.py
[Genesis] [03:03:27] [INFO] ╭─────────────────────────────────────────────────────────────────────────────────────╮
[Genesis] [03:03:27] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉│
[Genesis] [03:03:27] [INFO] ╰─────────────────────────────────────────────────────────────────────────────────────╯
[Genesis] [03:03:27] [INFO] Running on [AMD Ryzen 7 4800H with Radeon Graphics] with backend gs.cpu. Device memory: 17.91 GB.
[Genesis] [03:03:27] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.0, 🌱 seed: None, 📏 precision: '32', 🐛 debug: False, 🎨 theme: 'dark'.
[Genesis] [03:03:27] [INFO] Scene <2c97d62> created.
[Genesis] [03:03:27] [INFO] Adding <gs.RigidEntity>. idx: 0, uid: <f76964a>, morph: <gs.morphs.Plane>, material: <gs.materials.Rigid>.
Traceback (most recent call last):
  File "/home/wpc/Genesis/hello.py", line 15, in <module>
    plane = scene.add_entity(gs.morphs.Plane())
  File "/home/wpc/Genesis/genesis/utils/misc.py", line 38, in wrapper
    return method(self, *args, **kwargs)
  File "/home/wpc/Genesis/genesis/engine/scene.py", line 360, in add_entity
    entity = self._sim._add_entity(morph, material, surface, visualize_contact)
  File "/home/wpc/Genesis/genesis/engine/simulator.py", line 134, in _add_entity
    entity = self.rigid_solver.add_entity(self.n_entities, material, morph, surface, visualize_contact)
  File "/home/wpc/Genesis/genesis/engine/solvers/rigid/rigid_solver_decomp.py", line 63, in add_entity
    entity = entity_class(
  File "/home/wpc/Genesis/genesis/engine/entities/rigid_entity/rigid_entity.py", line 68, in __init__
    self._load_model()
  File "/home/wpc/Genesis/genesis/engine/entities/rigid_entity/rigid_entity.py", line 87, in _load_model
    self._load_primitive(self._morph, self._surface)
  File "/home/wpc/Genesis/genesis/engine/entities/rigid_entity/rigid_entity.py", line 189, in _load_primitive
    link._add_geom(
  File "/home/wpc/Genesis/genesis/engine/entities/rigid_entity/rigid_link.py", line 173, in _add_geom
    geom = RigidGeom(
  File "/home/wpc/Genesis/genesis/engine/entities/rigid_entity/rigid_geom.py", line 94, in __init__
    self._preprocess()
  File "/home/wpc/Genesis/genesis/engine/entities/rigid_entity/rigid_geom.py", line 213, in _preprocess
    gsd_dict = pkl.load(file)
EOFError: Ran out of input
[Genesis] [03:03:27] [INFO] 💤 Exiting Genesis and caching compiled kernels...

**Comment by YilingQiao** [comment]
Can you print the `self._gsd_path`, delete that file, and run again? Looks like the cache file is broken.
